version: '3.8'
services:
  mysql:
    build: .
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jeelaqua_water_db

volumes:
  mysql_data:
